version: '3'

services:
    web:
        build: .
        ports:
            - "4000:4000"
        volumes:
            - .:/usr/src/inventory-management
        depends_on:
            - db

    db:
        image: "postgres:9.6.3"
        volumes:
            - db-data:/var/lib/postgresql/data

volumes:
    db-data:

